fn main() {
    let dir =
        std::path::PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap()).join("resources");
    let _ = std::fs::create_dir_all(&dir);
    let js = dir.join("fund-w3a.js");
    if !js.exists() {
        let _ = std::fs::write(
            &js,
            b"window.RootmodeW3A={start:function(){return Promise.reject(new Error('wallet modal not built'));}};\n",
        );
    }
    let css = dir.join("fund-w3a.css");
    if !css.exists() {
        let _ = std::fs::write(
            &css,
            b"/* wallet modal css is generated by npm run fund:w3a */\n",
        );
    }
    println!("cargo:rerun-if-changed=resources/fund-w3a.js");
    println!("cargo:rerun-if-changed=resources/fund-w3a.css");
    println!("cargo:rerun-if-env-changed=ROOTMODE_STRIPE_SECRET_KEY");
    println!("cargo:rerun-if-env-changed=ROOTMODE_STRIPE_PUBLISHABLE_KEY");
    tauri_build::build();
}
